version: "3"
services:
  ml_app:
    container_name: "python_ml_experiment"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: python_ml_experiment
    ports:
      - "8000:8000"
    working_dir: /home/app/
    volumes:
      - ./:/home/app
    tty: true # コンテナを起動させ続ける
    deploy:
      resources:
        limits:
          memory: 4g
