version: "3"
services:
  app:
    container_name: "python_ml_experiment"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: python_ml_experiment
    ports:
      - "8889:8889"
    volumes:
      - $PWD:/home/ML_experiment
    tty: true # コンテナを起動させ続ける
